# src/utils/file_utils.py

import json
from pathlib import Path
import logging

logger = logging.getLogger(__name__)

def find_pdfs_in_directory(directory_path: Path) -> list[Path]:
    """
    Recursively finds all PDF files within a given directory.

    Args:
        directory_path: The path to the directory to search.

    Returns:
        A list of Path objects for each found PDF file.
    """
    if not directory_path.is_dir():
        logger.error(f"Provided path is not a directory: {directory_path}")
        return []
    
    logger.info(f"Searching for PDF files in '{directory_path}'...")
    pdf_files = list(directory_path.rglob("*.pdf"))
    logger.info(f"Found {len(pdf_files)} PDF file(s).")
    return pdf_files

def save_json_output(data: dict, output_dir: Path, original_filename: str):
    """
    Saves the final extracted data dictionary as a JSON file.

    Args:
        data: The dictionary containing the extracted data.
        output_dir: The directory where the JSON file will be saved (from --output argument).
        original_filename: The name of the original PDF file, used for the output filename.
    """
    try:
        output_dir.mkdir(parents=True, exist_ok=True)
        
        output_filename = Path(original_filename).stem + ".json"
        output_path = output_dir / output_filename
        
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=4)
            
        logger.info(f"Successfully saved final JSON output to '{output_path}'")
    except Exception as e:
        logger.error(f"Failed to save JSON output for {original_filename}. Error: {e}", exc_info=True)

# --- NEW FUNCTION ADDED HERE ---
def save_markdown_output(markdown_content: str, output_dir: Path, original_filename: str):
    """
    Saves the intermediate parsed markdown content to a text file for debugging.

    Args:
        markdown_content: The string content generated by the parser.
        output_dir: The specific, hardcoded directory where the markdown file will be saved.
        original_filename: The name of the original PDF file.
    """
    try:
        # Ensure the hardcoded output directory exists
        output_dir.mkdir(parents=True, exist_ok=True)
        
        # Create a descriptive filename for the intermediate output
        output_filename = Path(original_filename).stem + "_parsed_output.md"
        output_path = output_dir / output_filename
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(markdown_content)
            
        logger.info(f"Successfully saved intermediate markdown output to '{output_path}'")
    except Exception as e:
        logger.error(f"Failed to save intermediate markdown output for {original_filename}. Error: {e}", exc_info=True)